---
format_version: 2
pipelines:
  pipeline-test:
    group: test
    label_template: "${COUNT}-${git[:7]}"
    enable_vault: true
    environment_variables:
      ROLE_ID: '{{SECRET:[vault][test1]}}'
      SECRET_ID: '{{SECRET:[vault][test2]}}'
    materials:
      git:
        git: git@github.com:anrock-sc/repo-test.git
    stages:
      - build:
          jobs:
            build:
              tasks:
               - exec:
                   command: make
